# Generated by Django 3.2.16 on 2022-12-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Des', models.TextField()),
                ('img', models.ImageField(upload_to='Service')),
            ],
        ),
    ]
