# Generated by Django 3.2.16 on 2022-12-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='img',
            new_name='image',
        ),
    ]
