# Generated by Django 3.2.16 on 2022-12-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_rename_image_testimonials_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='images',
            new_name='image',
        ),
    ]
